"use client";

import { useEffect,useState } from "react";
import { api,formatDate,PRIORITY_CLASS,STATUSES,STATUS_LABELS,type Task } from "@/lib/api";
import { ArrowLeft,ArrowRight,CalendarDays,Check,Flag,Plus } from "@/components/icons";
import { TaskDialog } from "@/components/task-dialog";
import { useShell } from "@/components/app-shell";

export default function BoardPage(){const [tasks,setTasks]=useState<Task[]>([]);const [loading,setLoading]=useState(true);const [dialog,setDialog]=useState(false);const [error,setError]=useState("");const {notify}=useShell();async function refresh(){try{const res=await api<{tasks:Task[]}>("tasks");setTasks(res.tasks);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load your board");}finally{setLoading(false);}}useEffect(()=>{let active=true;api<{tasks:Task[]}>("tasks").then(res=>{if(active)setTasks(res.tasks);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load your board");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  async function move(task:Task,to:Task["status"]){if(to==="completed"&&!window.confirm(`Mark “${task.title}” complete?`))return;try{await api(`tasks/${task.id}/move`,{method:"POST",body:JSON.stringify({status:to})});notify(to==="completed"?"Task completed — nice work":"Task moved to "+STATUS_LABELS[to].toLowerCase());await refresh();}catch(e){notify(e instanceof Error?e.message:"Could not move task");}}
  return <><div className="page-head"><div><h1 className="display">Keep the work moving.</h1><p>A simple view from first thought to finished work.</p></div><button className="btn" onClick={()=>setDialog(true)}><Plus size={16}/> New task</button></div>{error&&<div className="message message-error">{error}</div>}<div className="board-guidance"><span><span className="board-hint-dot"/> Your flow, at a glance</span><span>Choose an arrow on a card to move it through your workflow.</span></div>
    <section className="board">{STATUSES.map((status,index)=>{const column=tasks.filter(t=>t.status===status);return <div className={`board-column board-column-${status}`} key={status}><div className="column-head"><div className="column-title"><i className={`column-dot ${status}`}/>{STATUS_LABELS[status]}<span className="column-count">{column.length}</span></div><button className="column-menu" title={`Add task to ${STATUS_LABELS[status]}`} onClick={()=>setDialog(true)}><Plus size={14}/></button></div><div className="board-stack">{loading?<><div className="skeleton board-skeleton"/><div className="skeleton board-skeleton"/></>:column.length?column.map(task=><article className="board-card" key={task.id}><div className="board-card-top"><span className="board-category">{task.category||"PERSONAL"}</span><span className={`priority-dot ${task.priority}`} title={`${task.priority} priority`}/></div><h3>{task.title}</h3>{task.description&&<p className="board-desc">{task.description}</p>}<div className="board-meta"><span className={`pill ${PRIORITY_CLASS[task.priority]}`}><Flag size={10}/>{task.priority}</span>{task.due_date&&<span className={`board-date ${task.overdue?"overdue-text":""}`}><CalendarDays size={11}/>{formatDate(task.due_date)}</span>}</div><div className="board-actions">{status==="completed"?<button className="mini-action" onClick={()=>void move(task,"in_progress")}><ArrowLeft size={12}/> Reopen</button>:<>{(status==="in_progress"||status==="blocked")&&<button className="mini-action" title="Move to previous stage" onClick={()=>void move(task,status==="blocked"?"in_progress":"backlog")}><ArrowLeft size={12}/></button>}<button className="mini-action" title="Move to next stage" onClick={()=>void move(task,status==="backlog"?"in_progress":status==="in_progress"?"blocked":"completed")}>{status==="blocked"?<><Check size={12}/> Complete</>:<>Move forward <ArrowRight size={12}/></>}</button></>}</div></article>):<div className="board-empty">{index===0?"Ideas land here":"Nothing here yet"}</div>}</div></div>;})}</section>{dialog&&<TaskDialog onClose={()=>setDialog(false)} onSaved={async message=>{setDialog(false);notify(message);await refresh();}}/>}</>;
}
