"use client";

import { useEffect,useMemo,useState } from "react";
import { api,formatDate,STATUS_LABELS,type Task } from "@/lib/api";
import { ArrowRight,FolderKanban,Mail,Plus,Users } from "@/components/icons";
import { useShell } from "@/components/app-shell";
import { useLiveRefresh } from "@/lib/use-live-refresh";

type Team={team_id:number;name:string;created_at:string};
export default function TeamsPage(){const [teams,setTeams]=useState<Team[]>([]);const [selected,setSelected]=useState<number|null>(null);const [teamTasks,setTeamTasks]=useState<Task[]>([]);const [myTasks,setMyTasks]=useState<Task[]>([]);const [name,setName]=useState("");const [invite,setInvite]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const {notify}=useShell();
  async function loadTeams(){const data=await api<{teams:Team[]}>("teams");setTeams(data.teams);const first=data.teams[0]?.team_id??null;setSelected(first);if(first)await loadTasks(first);}
  async function loadTasks(teamId:number){const [team,personal]=await Promise.all([api<{tasks:Task[]}>(`teams/${teamId}/tasks`),api<{tasks:Task[]}>("tasks")]);setTeamTasks(team.tasks);setMyTasks(personal.tasks.filter(t=>t.status!=="completed"));}
  async function refresh(){const data=await api<{teams:Team[]}>("teams");setTeams(data.teams);const teamId=data.teams.some(team=>team.team_id===selected)?selected:data.teams[0]?.team_id??null;if(teamId!==selected)setSelected(teamId);if(teamId)await loadTasks(teamId);else{setTeamTasks([]);setMyTasks([]);}}
  useLiveRefresh(refresh);
  useEffect(()=>{let active=true;api<{teams:Team[]}>("teams").then(data=>{if(!active)return;setTeams(data.teams);const first=data.teams[0]?.team_id??null;setSelected(first);if(first)api<{tasks:Task[]}>(`teams/${first}/tasks`).then(result=>{if(active)setTeamTasks(result.tasks);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load team tasks");});}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load teams");});api<{tasks:Task[]}>("tasks").then(data=>{if(active)setMyTasks(data.tasks.filter(t=>t.status!=="completed"));}).catch(()=>undefined);return()=>{active=false;};},[]);
  const active=useMemo(()=>teams.find(team=>team.team_id===selected),[teams,selected]);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{await api("teams",{method:"POST",body:JSON.stringify({name})});setName("");await loadTeams();notify("Your team space is ready");}catch(e){setError(e instanceof Error?e.message:"Could not create team");}finally{setBusy(false);}}
  async function assign(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);try{await api(`teams/${selected}/tasks`,{method:"POST",body:JSON.stringify({task_id:Number((event.currentTarget.elements.namedItem("task") as HTMLSelectElement).value)})});await loadTasks(selected);notify("Task added to the team board");}catch(e){setError(e instanceof Error?e.message:"Could not assign task");}finally{setBusy(false);}}
  async function addMember(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);try{await api(`teams/${selected}/members`,{method:"POST",body:JSON.stringify({email:invite})});setInvite("");notify("Member added to the team");}catch(e){setError(e instanceof Error?e.message:"Could not add member");}finally{setBusy(false);}}
  return <><div className="page-head"><div><h1 className="display">Better work, together.</h1><p>Give shared work a home and bring people into the plan.</p></div></div>{error&&<div className="message message-error team-error">{error}</div>}<div className="team-layout"><aside className="surface team-list-panel"><div className="team-list-head"><span className="eyebrow">YOUR SPACES</span><span className="team-total">{teams.length}</span></div>{teams.length?<nav className="team-picker">{teams.map((team,index)=><button key={team.team_id} className={`team-item ${selected===team.team_id?"active":""}`} onClick={()=>{setSelected(team.team_id);void loadTasks(team.team_id).catch(e=>setError(e instanceof Error?e.message:"Could not load team tasks"));}}><span className={`team-avatar team-color-${index%4}`}>{team.name.slice(0,1).toUpperCase()}</span><span className="team-pick-copy"><strong>{team.name}</strong><small>Shared workspace</small></span><ArrowRight size={13}/></button>)}</nav>:<div className="team-no-space">No team spaces yet. Create one to share tasks with your people.</div>}<form className="create-team-form" onSubmit={create}><label htmlFor="team-name">Create a team</label><div className="team-create-row"><input id="team-name" maxLength={200} placeholder="e.g. Capstone project" value={name} onChange={e=>setName(e.target.value)} required/><button className="icon-btn" disabled={busy} title="Create team"><Plus size={16}/></button></div></form></aside>
    <section className="surface team-content team-content-modern">{active?<><div className="team-page-head"><div className="team-title-wrap"><span className="team-avatar team-avatar-large">{active.name.slice(0,1).toUpperCase()}</span><div><h2>{active.name}</h2><p>Started {formatDate(active.created_at.slice(0,10))} · {teamTasks.length} shared {teamTasks.length===1?"task":"tasks"}</p></div></div><span className="team-private"><Users size={13}/> Private team</span></div><div className="team-actions-row"><form className="inline-team-form" onSubmit={assign}><label htmlFor="team-task">Share a task</label><select id="team-task" name="task" required disabled={!myTasks.length}><option value="">{myTasks.length?"Choose one of your tasks":"No open tasks to share"}</option>{myTasks.map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select><button className="btn" disabled={busy||!myTasks.length}><Plus size={14}/> Add</button></form><form className="inline-team-form invite-form" onSubmit={addMember}><label htmlFor="member-email">Invite a teammate</label><input id="member-email" type="email" placeholder="teammate@example.com" value={invite} onChange={e=>setInvite(e.target.value)} required/><button className="btn btn-secondary" disabled={busy}><Mail size={14}/> Invite</button></form></div><div className="team-board-head"><div><span className="eyebrow">SHARED TASKS</span><h3>What the team is working on</h3></div></div>{teamTasks.length?<div className="team-task-list">{teamTasks.map(task=><article className="team-task-row" key={task.id}><div className="team-task-glyph"><FolderKanban size={15}/></div><div className="team-task-copy"><strong>{task.title}</strong><span>{task.category||"Team task"}{task.due_date?` · Due ${formatDate(task.due_date)}`:""}</span></div><span className={`pill ${task.status==="completed"?"pill-green":task.status==="blocked"?"pill-orange":"pill-neutral"}`}>{STATUS_LABELS[task.status]}</span></article>)}</div>:<div className="team-empty"><span className="empty-icon"><Users size={18}/></span><strong>Start with one shared task.</strong><span>Choose an open task above to bring it onto this team board.</span></div>}</>:<div className="team-welcome"><span className="team-welcome-art"><Users size={24}/></span><h2>Work finds its rhythm together.</h2><p>Create a team space to share tasks, align on what matters, and keep everyone in step.</p><form className="team-welcome-form" onSubmit={create}><input placeholder="Name your team space" maxLength={200} value={name} onChange={e=>setName(e.target.value)} required/><button className="btn" disabled={busy}><Plus size={15}/> Create space</button></form></div>}</section></div></>;
}
