"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api, formatDate, relativeTime, type Task } from "@/lib/api";
import { Activity, ArrowRight, ArrowUpRight, CalendarDays, Check, CheckCheck, Clock3, Flag, Plus, Target, TrendingUp } from "@/components/icons";
import { TaskDialog } from "@/components/task-dialog";
import { useShell } from "@/components/app-shell";
import { useLiveRefresh } from "@/lib/use-live-refresh";

type Metrics={tasks_completed_today:number;tasks_completed_week:number;overdue_count:number;high_priority_count:number;completion_rate:number};type ActivityItem={id:number;task_id:number;event:string;timestamp:string;title:string;status:string};
const blank:Metrics={tasks_completed_today:0,tasks_completed_week:0,overdue_count:0,high_priority_count:0,completion_rate:0};
export default function DashboardPage(){
  const {user,notify}=useShell();const [metrics,setMetrics]=useState(blank);const [tasks,setTasks]=useState<Task[]>([]);const [activity,setActivity]=useState<ActivityItem[]>([]);const [loading,setLoading]=useState(true);const [dialog,setDialog]=useState(false);const [error,setError]=useState("");
  async function refresh(){try{const [m,t,h]=await Promise.all([api<Metrics>("dashboard"),api<{tasks:Task[]}>("tasks"),api<{items:ActivityItem[]}>("history?limit=5")]);setMetrics(m);setTasks(t.tasks);setActivity(h.items);}catch(e){setError(e instanceof Error?e.message:"Could not load your workspace");}finally{setLoading(false);}}
  useLiveRefresh(refresh);
  useEffect(()=>{let active=true;Promise.all([api<Metrics>("dashboard"),api<{tasks:Task[]}>("tasks"),api<{items:ActivityItem[]}>("history?limit=5")]).then(([m,t,h])=>{if(active){setMetrics(m);setTasks(t.tasks);setActivity(h.items);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load your workspace");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const completed=tasks.filter(t=>t.status==="completed").length;const completion=tasks.length?Math.round(completed/tasks.length*100):0;const next=tasks.filter(t=>t.status!=="completed").slice(0,4);
  const week=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const done=tasks.filter(t=>t.status==="completed"&&new Date(t.updated_at.replace(" ","T")+"Z").toDateString()===d.toDateString()).length;return{day:new Intl.DateTimeFormat("en",{weekday:"short"}).format(d),done,total:Math.max(done,Math.ceil(tasks.filter(t=>t.status!=="completed").length/7))};});
  return <><div className="page-head"><div><h1 className="display">A little more flow, {user?.name.split(" ")[0]}.</h1><p>Here’s a clear view of what’s moving today.</p></div><button className="btn" onClick={()=>setDialog(true)}><Plus size={16}/> New task</button></div>{error&&<div className="message message-error">{error}</div>}
    <section className="stat-grid"><Metric label="Completed today" value={metrics.tasks_completed_today} caption="A steady start" icon={<CheckCheck size={16}/>} tone="green" loading={loading}/><Metric label="Due soon" value={tasks.filter(t=>t.due_date&&t.status!=="completed"&&t.due_date>=new Date().toISOString().slice(0,10)).length} caption="Keep the next step close" icon={<Clock3 size={16}/>} tone="blue" loading={loading}/><Metric label="Overdue" value={metrics.overdue_count} caption={metrics.overdue_count?"Worth a quick review":"You’re all caught up"} icon={<CalendarDays size={16}/>} tone="orange" loading={loading}/><Metric label="High priority" value={metrics.high_priority_count} caption={`${completion}% of your tasks completed`} icon={<Flag size={16}/>} tone="purple" loading={loading}/></section>
    <div className="dash-grid"><section className="surface panel"><div className="panel-head"><div><h2>Your momentum</h2><p>A gentle look at the last seven days</p></div><span className="momentum-badge"><TrendingUp size={13}/> {metrics.tasks_completed_week} this week</span></div><div className="chart-area"><div className="chart-grid-lines"><span>4</span><span>3</span><span>2</span><span>1</span></div><div className="chart">{week.map((d,i)=><div className="chart-day" key={`${d.day}-${i}`}><div className="chart-pair"><i className="chart-bar" style={{height:`${Math.max(8,Math.min(100,d.total*28))}%`}}/><i className={`chart-bar active ${i===6?"chart-today":""}`} style={{height:`${Math.max(5,Math.min(100,d.done*28))}%`}}/></div><span className="chart-label">{d.day}</span></div>)}</div></div><div className="chart-legend"><span><i/>Tasks in motion</span><span><i className="legend-complete"/>Completed</span></div></section>
    <section className="surface panel"><div className="panel-head"><div><h2>Coming up</h2><p>Your next few open tasks</p></div><Link href="/tasks" className="subtle-link">See all <ArrowRight size={13}/></Link></div>{loading?<div className="loading-stack"><i className="skeleton"/><i className="skeleton"/><i className="skeleton"/></div>:next.length?<div className="upcoming-list">{next.map(task=><div className="upcoming-item" key={task.id}><button className="task-check" title="Mark completed" onClick={async()=>{try{await api(`tasks/${task.id}/move`,{method:"POST",body:JSON.stringify({status:"completed"})});notify("Nice work — task complete");await refresh();}catch(e){notify(e instanceof Error?e.message:"Could not complete task");}}}><Check size={13}/></button><div className="upcoming-copy"><strong>{task.title}</strong><span>{task.category||"Personal"} · {task.due_date?`Due ${formatDate(task.due_date)}`:"No due date"}</span></div><span className={`pill ${task.priority==="high"?"pill-orange":"pill-green"}`}>{task.priority}</span></div>)}</div>:<div className="empty small-empty"><strong>A little breathing room.</strong>Add a task when you’re ready.</div>}<div className="panel-bottom-link"><Link href="/board">Open your workflow board <ArrowUpRight size={14}/></Link></div></section></div>
    <div className="dash-grid bottom-grid"><section className="surface panel"><div className="panel-head"><div><h2>Recent activity</h2><p>Small steps add up</p></div><Link href="/history" className="subtle-link">Full history <ArrowRight size={13}/></Link></div>{loading?<div className="loading-stack"><i className="skeleton"/><i className="skeleton"/></div>:activity.length?<div className="activity-list">{activity.slice(0,4).map(item=><div className="activity-item" key={item.id}><span className="activity-dot"><Activity size={13}/></span><div><div className="activity-title">{eventTitle(item.event)} <span className="activity-task">{item.title}</span></div><div className="activity-meta">{item.status.replaceAll("_"," ")}</div></div><time className="activity-time">{relativeTime(item.timestamp)}</time></div>)}</div>:<div className="empty"><strong>Your story starts here.</strong>Task updates will show up as you go.</div>}</section>
    <section className="surface focus-card"><div className="focus-art"><div className="focus-ring ring-a"/><div className="focus-ring ring-b"/><div className="focus-icon"><Target size={21}/></div></div><div className="eyebrow">One step at a time</div><h2>Focus on what’s next.</h2><p>You have <strong>{tasks.filter(t=>t.status!=="completed").length} open tasks</strong>. Pick one and give it your attention.</p><Link className="btn btn-secondary focus-link" href="/tasks">Choose a task <ArrowRight size={14}/></Link><div className="focus-note"><Check size={13}/> Progress is a practice, not a finish line.</div></section></div>
    {dialog&&<TaskDialog onClose={()=>setDialog(false)} onSaved={async message=>{setDialog(false);notify(message);await refresh();}}/>}</>;
}
function Metric({label,value,caption,icon,tone,loading}:{label:string;value:number;caption:string;icon:React.ReactNode;tone:string;loading:boolean}){return <article className="surface stat-card"><div className="stat-top"><span>{label}</span><span className={`stat-icon tone-${tone}`}>{icon}</span></div>{loading?<div className="skeleton stat-skeleton"/>:<div className="stat-value">{value}</div>}<div className="stat-caption">{caption}</div></article>}
function eventTitle(event:string){if(event==="created")return "Task created";if(event.startsWith("moved:"))return `Moved to ${event.split("->")[1]?.replaceAll("_"," ")||"a new stage"}`;return event==="overdue"?"Due date passed":"Task updated";}
