"use client";

import { useMemo,useState } from "react";
import { api,formatDate,PRIORITY_CLASS,STATUS_LABELS,type Task } from "@/lib/api";
import { CalendarDays,Check,Flag,ListFilter,MoreHorizontal,Plus,Search,Trash2 } from "@/components/icons";
import { TaskDialog } from "@/components/task-dialog";
import { useShell } from "@/components/app-shell";
import { useLiveRefresh } from "@/lib/use-live-refresh";

type Filter="all"|"open"|"completed"|"high";
export default function TasksPage(){const [tasks,setTasks]=useState<Task[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [filter,setFilter]=useState<Filter>("all");const [query,setQuery]=useState("");const [dialog,setDialog]=useState(false);const [editing,setEditing]=useState<Task|undefined>();const {notify}=useShell();
  async function refresh(){try{const result=await api<{tasks:Task[]}>("tasks");setTasks(result.tasks);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load tasks");}finally{setLoading(false);}}
  useLiveRefresh(refresh);
  const filtered=useMemo(()=>tasks.filter(t=>(filter==="all"||filter==="open"&&t.status!=="completed"||filter==="completed"&&t.status==="completed"||filter==="high"&&t.priority==="high")&&`${t.title} ${t.description||""} ${t.category||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.status===b.status?(a.due_date||"9999").localeCompare(b.due_date||"9999"):a.status==="completed"?1:-1),[tasks,filter,query]);
  async function remove(task:Task){if(!window.confirm(`Delete “${task.title}”? This cannot be undone.`))return;try{await api(`tasks/${task.id}`,{method:"DELETE"});notify("Task deleted");await refresh();}catch(e){notify(e instanceof Error?e.message:"Could not delete task");}}
  const counts={all:tasks.length,open:tasks.filter(t=>t.status!=="completed").length,completed:tasks.filter(t=>t.status==="completed").length,high:tasks.filter(t=>t.priority==="high").length};
  return <><div className="page-head"><div><h1 className="display">Your tasks, in good order.</h1><p>Capture it, clarify the next step, and keep moving.</p></div><button className="btn" onClick={()=>{setEditing(undefined);setDialog(true);}}><Plus size={16}/> Add a task</button></div>
    <section className="surface task-surface"><div className="task-controls"><div className="filter-row">{(["all","open","completed","high"] as Filter[]).map(item=><button key={item} className={`filter-chip ${filter===item?"active":""}`} onClick={()=>setFilter(item)}>{({all:"Everything",open:"In progress",completed:"Completed",high:"High priority"})[item]} <span>{counts[item]}</span></button>)}</div><div className="search-wrap"><Search size={15}/><input aria-label="Filter tasks" placeholder="Filter your tasks…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear filter">×</button>}</div></div>
      <div className="task-table-head"><span>Task</span><span>Status</span><span>Priority</span><span className="hide-md">Due date</span><span/></div>
      {error&&<div className="message message-error task-error">{error}</div>}{loading?<div className="tasks-loading">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>:filtered.length?<div className="task-list">{filtered.map(task=><article className="task-row task-row-modern" key={task.id}><div className="task-main"><button className={`task-check ${task.status==="completed"?"checked":""}`} onClick={async()=>{const status=task.status==="completed"?"in_progress":"completed";try{await api(`tasks/${task.id}/move`,{method:"POST",body:JSON.stringify({status})});notify(status==="completed"?"Task completed":"Task reopened");await refresh();}catch(e){notify(e instanceof Error?e.message:"Could not update task");}}} title={task.status==="completed"?"Reopen task":"Mark complete"}>{task.status==="completed"?<Check size={13}/>:null}</button><div className="task-copy"><strong>{task.title}</strong><span>{task.category||"Personal"}{task.estimated_minutes?` · ${task.estimated_minutes} min`:""}</span></div></div><div><span className={`pill ${task.status==="completed"?"pill-green":task.status==="blocked"?"pill-orange":"pill-neutral"}`}><i className={`status-point ${task.status}`}/>{STATUS_LABELS[task.status]}</span></div><div><span className={`pill ${PRIORITY_CLASS[task.priority]}`}><Flag size={11}/>{task.priority}</span></div><div className="task-cell hide-md"><span className={task.overdue?"overdue-text":""}><CalendarDays size={13}/>{formatDate(task.due_date)}</span></div><div className="row-actions"><button className="icon-btn task-action" title="Edit task" onClick={()=>{setEditing(task);setDialog(true);}}><MoreHorizontal size={16}/></button><button className="icon-btn task-action delete-action" title="Delete task" onClick={()=>void remove(task)}><Trash2 size={14}/></button></div></article>)}</div>:<div className="empty task-empty"><span className="empty-icon"><ListFilter size={19}/></span><strong>{query?"No matching tasks":"A fresh page."}</strong><span>{query?"Try another filter or phrase.":"Add a task to get your plans out of your head and into motion."}</span>{!query&&<button className="btn empty-action" onClick={()=>setDialog(true)}><Plus size={15}/> Add the first task</button>}</div>}
    </section>{dialog&&<TaskDialog task={editing} onClose={()=>setDialog(false)} onSaved={async message=>{setDialog(false);setEditing(undefined);notify(message);await refresh();}}/>}</>;
}
