import Link from "next/link";
import { ArrowRight, Check, CheckCheck, CircleHelp, Clock3, Sparkles, Target, TrendingUp, Zap } from "@/components/icons";

export default function HomePage() {
  return <main className="landing">
    <nav className="landing-nav"><Link href="/" className="brand"><span className="brand-mark"><CheckCheck size={17}/></span><span>flowstate<span className="brand-period">.</span></span></Link><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#features">Features</a><Link href="/login">Sign in</Link><Link href="/register" className="btn landing-nav-cta">Get started <ArrowRight size={15}/></Link></div></nav>
    <section className="landing-hero"><div className="landing-copy"><div className="eyebrow"><Sparkles size={13}/> A calmer way to get things done</div><h1>Make progress feel <span>natural.</span></h1><p>Less juggling. More meaningful work. Bring your plans, priorities, and people into one thoughtful workspace.</p><div className="landing-cta"><Link href="/register" className="btn landing-main-cta">Create your free space <ArrowRight size={16}/></Link><Link href="/login" className="btn btn-secondary">Sign in</Link></div><div className="landing-trust"><span><Check size={13}/> Private by design</span><span><Check size={13}/> Your pace, your plan</span></div></div>
      <div className="landing-visual" aria-label="Preview of Flowstate's task dashboard"><div className="orbit"/><div className="float-chip chip-one"><strong>3 priorities</strong><span>for a clear day</span></div><div className="float-chip chip-two"><strong>+24%</strong><span>weekly momentum</span></div><div className="dash-preview"><div className="preview-top"><div><span className="eyebrow">TUESDAY, OCT 06</span><strong style={{display:"block",marginTop:4}}>Your week at a glance</strong></div><div className="preview-avatar">J</div></div><div className="preview-chart-label"><span>Focus time</span><strong>12.5h <small>this week</small></strong></div><div className="preview-graph"><i style={{height:"33%"}}/><i style={{height:"52%"}}/><i style={{height:"42%"}}/><i style={{height:"76%"}}/><i style={{height:"60%"}}/><i style={{height:"95%"}}/><i style={{height:"68%"}}/></div><div className="preview-section"><div className="preview-section-title">Up next <span>3 tasks</span></div><div className="preview-tasks"><div className="preview-task"><span className="preview-check"/> Outline launch plan <span className="preview-task-date">10:30</span></div><div className="preview-task"><span className="preview-check"/> Review project brief <span className="preview-task-date">1:00</span></div><div className="preview-task"><span className="preview-check"/> Team check-in <span className="preview-task-date">3:30</span></div></div></div></div></div></section>
    <section className="landing-proof" id="features"><span>Designed for real workdays</span><strong><Target size={15}/> Priorities</strong><strong><Clock3 size={15}/> Gentle structure</strong><strong><TrendingUp size={15}/> Visible progress</strong><strong><CircleHelp size={15}/> Clear next steps</strong></section>
    <section className="landing-how" id="how-it-works"><div className="how-heading"><div className="eyebrow">A little more flow</div><h2>From scattered to steady.</h2><p>Flowstate keeps the important things easy to see and even easier to move forward.</p></div><div className="how-cards"><article className="how-card"><span>01</span><div className="how-icon"><Target size={18}/></div><h3>Choose what matters</h3><p>Capture work, set a due date, and let smart priorities help you decide what comes next.</p></article><article className="how-card"><span>02</span><div className="how-icon"><Zap size={18}/></div><h3>Move one step at a time</h3><p>See every task across a simple board, from the first idea to finished work.</p></article><article className="how-card"><span>03</span><div className="how-icon"><TrendingUp size={18}/></div><h3>Notice your progress</h3><p>Reflect on your days, coordinate with your team, and build a rhythm that works.</p></article></div></section>
    <footer className="landing-footer"><Link href="/" className="brand"><span className="brand-mark"><CheckCheck size={16}/></span><span>flowstate.</span></Link><span>Make good work a little easier.</span><Link className="link" href="/register">Start your workspace <ArrowRight size={14}/></Link></footer>
  </main>;
}
