"use client";

import { useState } from "react";
import { api } from "@/lib/api";
import { CheckCheck,KeyRound,LoaderCircle,ShieldCheck,UserRound } from "@/components/icons";
import { useShell } from "@/components/app-shell";

export default function SettingsPage(){const {user,refreshUser,notify}=useShell();const [name,setName]=useState(user?.name||"");const [current,setCurrent]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [profileBusy,setProfileBusy]=useState(false);const [passwordBusy,setPasswordBusy]=useState(false);const [profileMessage,setProfileMessage]=useState("");const [passwordMessage,setPasswordMessage]=useState("");const [error,setError]=useState("");
  async function saveProfile(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setProfileBusy(true);setError("");setProfileMessage("");try{await api("profile",{method:"PATCH",body:JSON.stringify({name})});await refreshUser();setProfileMessage("Your profile is up to date.");notify("Profile saved");}catch(e){setError(e instanceof Error?e.message:"Could not save profile");}finally{setProfileBusy(false);}}
  async function changePassword(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPasswordMessage("");setError("");if(password!==confirm){setError("Your new passwords don’t match.");return;}setPasswordBusy(true);try{await api("auth/change-password",{method:"POST",body:JSON.stringify({current_password:current,new_password:password})});setPasswordMessage("Password updated successfully.");setCurrent("");setPassword("");setConfirm("");notify("Password changed");}catch(e){setError(e instanceof Error?e.message:"Could not update password");}finally{setPasswordBusy(false);}}
  return <><div className="page-head"><div><h1 className="display">Make Flowstate yours.</h1><p>Your personal details and account security.</p></div></div>{error&&<div className="message message-error settings-error">{error}</div>}<div className="settings-grid"><section className="surface settings-card settings-card-modern"><div className="settings-card-icon"><UserRound size={17}/></div><h2>Personal details</h2><p>Keep your workspace profile current.</p><form className="settings-form" onSubmit={saveProfile}><div className="field"><label htmlFor="profile-name">Display name</label><input id="profile-name" required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor="profile-email">Email address</label><input id="profile-email" value={user?.email||""} disabled/><span className="field-help">Your email is verified and can’t be changed here.</span></div>{profileMessage&&<div className="message message-success">{profileMessage}</div>}<button className="btn" disabled={profileBusy}>{profileBusy?<LoaderCircle size={16} className="spin"/>:<CheckCheck size={15}/>} Save profile</button></form></section>
    <section className="surface settings-card settings-card-modern"><div className="settings-card-icon"><KeyRound size={17}/></div><h2>Change password</h2><p>Use a unique password with at least 8 characters.</p><form className="settings-form" onSubmit={changePassword}><div className="field"><label htmlFor="current-password">Current password</label><input id="current-password" type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></div><div className="field"><label htmlFor="settings-password">New password</label><input id="settings-password" type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></div><div className="field"><label htmlFor="confirm-settings-password">Confirm new password</label><input id="confirm-settings-password" type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></div>{passwordMessage&&<div className="message message-success">{passwordMessage}</div>}<button className="btn btn-secondary" disabled={passwordBusy}>{passwordBusy?<LoaderCircle size={16} className="spin"/>:<ShieldCheck size={15}/>} Update password</button></form></section></div><div className="security-note"><ShieldCheck size={15}/><span><strong>Your account stays yours.</strong> Passwords are protected with bcrypt hashing, and your session cookie is HttpOnly.</span></div></>;
}
