"use client";

import { useEffect,useMemo,useState } from "react";
import { api,formatDate,STATUS_LABELS,type Task } from "@/lib/api";
import { ArrowLeft,ArrowRight,CalendarDays,Clock3,Plus } from "@/components/icons";
import { TaskDialog } from "@/components/task-dialog";

const monthNames=new Intl.DateTimeFormat("en",{month:"long",year:"numeric"});const weekdays=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function iso(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
export default function CalendarPage(){const [tasks,setTasks]=useState<Task[]>([]);const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const [selected,setSelected]=useState(()=>iso(new Date()));const [loading,setLoading]=useState(true);const [dialog,setDialog]=useState(false);
  async function refresh(){try{const result=await api<{tasks:Task[]}>("tasks");setTasks(result.tasks);}finally{setLoading(false);}}useEffect(()=>{let active=true;api<{tasks:Task[]}>("tasks").then(result=>{if(active)setTasks(result.tasks);}).catch(()=>undefined).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const first=new Date(month.getFullYear(),month.getMonth(),1);const offset=(first.getDay()+6)%7;const start=new Date(first);start.setDate(1-offset);const dates=Array.from({length:42},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);return date;});const selectedTasks=useMemo(()=>tasks.filter(t=>t.due_date===selected),[tasks,selected]);
  return <><div className="page-head"><div><h1 className="display">Your time, made visible.</h1><p>See what’s coming and make space for it.</p></div><button className="btn" onClick={()=>setDialog(true)}><Plus size={16}/> Add a task</button></div><div className="calendar-layout"><section className="surface calendar-card"><div className="calendar-title-row"><div><div className="eyebrow">PLAN WITH ROOM TO BREATHE</div><h2>{monthNames.format(month)}</h2></div><div className="calendar-nav"><button className="icon-btn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} aria-label="Previous month"><ArrowLeft size={15}/></button><button className="today-button" onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelected(iso(now));}}>Today</button><button className="icon-btn" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} aria-label="Next month"><ArrowRight size={15}/></button></div></div><div className="calendar-grid">{weekdays.map(day=><div key={day} className="calendar-weekday">{day}</div>)}{dates.map((date,i)=>{const key=iso(date);const dayTasks=tasks.filter(t=>t.due_date===key);const isToday=key===iso(new Date());return <button key={`${key}-${i}`} className={`calendar-day ${date.getMonth()!==month.getMonth()?"outside":""} ${selected===key?"selected":""} ${isToday?"today":""}`} onClick={()=>setSelected(key)}><span className="day-num">{date.getDate()}</span>{dayTasks.length>0&&<><div className="day-markers">{dayTasks.slice(0,4).map(t=><i className={`day-marker ${t.overdue?"overdue":""}`} key={t.id}/>)}</div><div className="day-count">{dayTasks.length} {dayTasks.length===1?"task":"tasks"}</div></>}</button>;})}</div></section><aside className="surface calendar-agenda"><div className="agenda-head"><div className="eyebrow">YOUR AGENDA</div><h2>{formatDate(selected)}</h2><p>{selectedTasks.length?`${selectedTasks.length} thing${selectedTasks.length===1?"":"s"} on your list`:"A little open space."}</p></div>{loading?<div className="loading-stack"><i className="skeleton"/><i className="skeleton"/></div>:selectedTasks.length?<div className="agenda-items">{selectedTasks.map(task=><article className="agenda-item" key={task.id}><div className={`agenda-line ${task.status}`}/><div><strong>{task.title}</strong><span>{task.category||"Personal"} · {STATUS_LABELS[task.status]}</span>{task.estimated_minutes&&<small><Clock3 size={11}/>{task.estimated_minutes} minutes</small>}</div></article>)}</div>:<div className="agenda-empty"><div className="agenda-empty-icon"><CalendarDays size={19}/></div><strong>Nothing scheduled.</strong><span>Give your plans a date when you’re ready.</span><button className="btn btn-secondary" onClick={()=>setDialog(true)}><Plus size={14}/> Add a task</button></div>}</aside></div>{dialog&&<TaskDialog onClose={()=>setDialog(false)} onSaved={async()=>{setDialog(false);await refresh();}}/>}</>;
}
